spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://server-starbank:vresatasrrkebn@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}




